// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/patient": {
    params: {};
  };
  "/patient/complete-profile": {
    params: {};
  };
  "/patient/chat/:practitioner": {
    params: {
      "practitioner": string;
    };
  };
  "/patient/find-doctors": {
    params: {};
  };
  "/patient/estimates/:providerId/:questionnaireId": {
    params: {
      "providerId": string;
      "questionnaireId": string;
    };
  };
  "/patient/profile/:doctorId": {
    params: {
      "doctorId": string;
    };
  };
  "/patient/qa/:providerId": {
    params: {
      "providerId": string;
    };
  };
  "/provider": {
    params: {};
  };
  "/provider/complete-profile": {
    params: {};
  };
  "/provider/patients": {
    params: {};
  };
  "/provider/patients/:patientId": {
    params: {
      "patientId": string;
    };
  };
  "/provider/patients/:patientId/chat": {
    params: {
      "patientId": string;
    };
  };
  "/provider/patients/:patientId/allergy": {
    params: {
      "patientId": string;
    };
  };
  "/provider/patients/:patientId/medication": {
    params: {
      "patientId": string;
    };
  };
  "/provider/patients/:patientId/immunization": {
    params: {
      "patientId": string;
    };
  };
  "/provider/patients/:patientId/health-condition": {
    params: {
      "patientId": string;
    };
  };
  "/provider/patients/:patientId/procedure": {
    params: {
      "patientId": string;
    };
  };
  "/provider/patients/:patientId/vital": {
    params: {
      "patientId": string;
    };
  };
  "/provider/patients/:patientId/result": {
    params: {
      "patientId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/patient" | "/patient/complete-profile" | "/patient/chat/:practitioner" | "/patient/find-doctors" | "/patient/estimates/:providerId/:questionnaireId" | "/patient/profile/:doctorId" | "/patient/qa/:providerId" | "/provider" | "/provider/complete-profile" | "/provider/patients" | "/provider/patients/:patientId" | "/provider/patients/:patientId/chat" | "/provider/patients/:patientId/allergy" | "/provider/patients/:patientId/medication" | "/provider/patients/:patientId/immunization" | "/provider/patients/:patientId/health-condition" | "/provider/patients/:patientId/procedure" | "/provider/patients/:patientId/vital" | "/provider/patients/:patientId/result";
  };
  "./routes/_index.tsx": {
    id: "./routes/_index";
    page: "/";
  };
  "./routes/_auth.login.tsx": {
    id: "./routes/_auth.login";
    page: "/login";
  };
  "./routes/patient/route.tsx": {
    id: "./routes/patient/route";
    page: "/patient" | "/patient/complete-profile" | "/patient/chat/:practitioner" | "/patient/find-doctors" | "/patient/estimates/:providerId/:questionnaireId" | "/patient/profile/:doctorId" | "/patient/qa/:providerId";
  };
  "./routes/patient/index.tsx": {
    id: "./routes/patient/index";
    page: "/patient";
  };
  "./routes/patient/complete-profile.tsx": {
    id: "./routes/patient/complete-profile";
    page: "/patient/complete-profile";
  };
  "./routes/patient/chat.tsx": {
    id: "./routes/patient/chat";
    page: "/patient/chat/:practitioner";
  };
  "./routes/patient/find-doctors.tsx": {
    id: "./routes/patient/find-doctors";
    page: "/patient/find-doctors";
  };
  "./routes/patient/estimates.tsx": {
    id: "./routes/patient/estimates";
    page: "/patient/estimates/:providerId/:questionnaireId";
  };
  "./routes/patient/doctor-profile.tsx": {
    id: "./routes/patient/doctor-profile";
    page: "/patient/profile/:doctorId";
  };
  "./routes/patient/qa.tsx": {
    id: "./routes/patient/qa";
    page: "/patient/qa/:providerId";
  };
  "./routes/provider/route.tsx": {
    id: "./routes/provider/route";
    page: "/provider" | "/provider/complete-profile" | "/provider/patients" | "/provider/patients/:patientId" | "/provider/patients/:patientId/chat" | "/provider/patients/:patientId/allergy" | "/provider/patients/:patientId/medication" | "/provider/patients/:patientId/immunization" | "/provider/patients/:patientId/health-condition" | "/provider/patients/:patientId/procedure" | "/provider/patients/:patientId/vital" | "/provider/patients/:patientId/result";
  };
  "./routes/provider/index.tsx": {
    id: "./routes/provider/index";
    page: "/provider";
  };
  "./routes/provider/complete-profile.tsx": {
    id: "./routes/provider/complete-profile";
    page: "/provider/complete-profile";
  };
  "./routes/provider/patients.tsx": {
    id: "./routes/provider/patients";
    page: "/provider/patients" | "/provider/patients/:patientId" | "/provider/patients/:patientId/chat" | "/provider/patients/:patientId/allergy" | "/provider/patients/:patientId/medication" | "/provider/patients/:patientId/immunization" | "/provider/patients/:patientId/health-condition" | "/provider/patients/:patientId/procedure" | "/provider/patients/:patientId/vital" | "/provider/patients/:patientId/result";
  };
  "./routes/provider/patient-by-id.tsx": {
    id: "./routes/provider/patient-by-id";
    page: "/provider/patients/:patientId" | "/provider/patients/:patientId/chat" | "/provider/patients/:patientId/allergy" | "/provider/patients/:patientId/medication" | "/provider/patients/:patientId/immunization" | "/provider/patients/:patientId/health-condition" | "/provider/patients/:patientId/procedure" | "/provider/patients/:patientId/vital" | "/provider/patients/:patientId/result";
  };
  "./routes/provider/chat.tsx": {
    id: "./routes/provider/chat";
    page: "/provider/patients/:patientId/chat";
  };
  "./routes/common/allergy/index.tsx": {
    id: "./routes/common/allergy/index";
    page: "/provider/patients/:patientId/allergy";
  };
  "./routes/common/medication/index.tsx": {
    id: "./routes/common/medication/index";
    page: "/provider/patients/:patientId/medication";
  };
  "./routes/common/immunization/index.tsx": {
    id: "./routes/common/immunization/index";
    page: "/provider/patients/:patientId/immunization";
  };
  "./routes/common/health-condition/index.tsx": {
    id: "./routes/common/health-condition/index";
    page: "/provider/patients/:patientId/health-condition";
  };
  "./routes/common/procedure/index.tsx": {
    id: "./routes/common/procedure/index";
    page: "/provider/patients/:patientId/procedure";
  };
  "./routes/common/vital/index.tsx": {
    id: "./routes/common/vital/index";
    page: "/provider/patients/:patientId/vital";
  };
  "./routes/common/result/index.tsx": {
    id: "./routes/common/result/index";
    page: "/provider/patients/:patientId/result";
  };
};